# Raw PDBbind Data Inspection

This notebook inspects the original PDBbind protein-ligand index and raw structure files. It intentionally does not read any files from `data/processed`.

In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.data_inspection import raw_data_quality_report

RAW_INDEX_PATH = PROJECT_ROOT / "data/raw/pdbbind2020/index/index/INDEX_general_PL.2020R1.lst"
RAW_COMPLEX_ROOT = PROJECT_ROOT / "data/raw/pdbbind2020/complexes/P-L"

RAW_INDEX_PATH, RAW_COMPLEX_ROOT

(PosixPath('/Users/songni/canvas.nosync/ai3624/final_project/data/raw/pdbbind2020/index/index/INDEX_general_PL.2020R1.lst'),
 PosixPath('/Users/songni/canvas.nosync/ai3624/final_project/data/raw/pdbbind2020/complexes/P-L'))

In [3]:
report = raw_data_quality_report(RAW_INDEX_PATH, RAW_COMPLEX_ROOT)
raw_df = report["raw_df"]
raw_df.head()

,line_number,pdb_id,resolution,release_year,raw_affinity,reference,ligand_name,comment,raw_line,index_parse_ok,...,protein_bytes,pocket_path,has_pocket,pocket_bytes,ligand_sdf_path,has_ligand_sdf,ligand_sdf_bytes,ligand_mol2_path,has_ligand_mol2,ligand_mol2_bytes
0,7,2tpi,2.10,1982,Kd=49uM,2tpi.pdf,2-mer,,2tpi 2.10 1982 Kd=49uM // 2tpi.pdf (2...,True,...,343278,/Users/songni/canvas.nosync/ai3624/final_proje...,True,87237,/Users/songni/canvas.nosync/ai3624/final_proje...,True,2766,/Users/songni/canvas.nosync/ai3624/final_proje...,True,3837
1,8,5tln,2.30,1982,Ki=0.43uM,5tln.pdf,BAN,incomplete ligand structure,5tln 2.30 1982 Ki=0.43uM // 5tln.pdf (B...,True,...,395361,/Users/songni/canvas.nosync/ai3624/final_proje...,True,101574,/Users/songni/canvas.nosync/ai3624/final_proje...,True,3211,/Users/songni/canvas.nosync/ai3624/final_proje...,True,4444
2,9,4tln,2.30,1982,Ki=190uM,4tln.pdf,LNO,,4tln 2.30 1982 Ki=190uM // 4tln.pdf (LNO),True,...,395685,/Users/songni/canvas.nosync/ai3624/final_proje...,True,84402,/Users/songni/canvas.nosync/ai3624/final_proje...,True,1843,/Users/songni/canvas.nosync/ai3624/final_proje...,True,2574
3,10,4cts,2.90,1984,Kd<10uM,4cts.pdf,OAA,,4cts 2.90 1984 Kd<10uM // 4cts.pdf (OAA),True,...,1128978,/Users/songni/canvas.nosync/ai3624/final_proje...,True,93312,/Users/songni/canvas.nosync/ai3624/final_proje...,True,849,/Users/songni/canvas.nosync/ai3624/final_proje...,True,1219
4,11,6rsa,NMR,1986,Ki=40uM,6rsa.pdf,UVC,,6rsa NMR 1986 Ki=40uM // 6rsa.pdf (UVC),True,...,179658,/Users/songni/canvas.nosync/ai3624/final_proje...,True,81810,/Users/songni/canvas.nosync/ai3624/final_proje...,True,2586,/Users/songni/canvas.nosync/ai3624/final_proje...,True,3605

## Dataset Size

In [4]:
report["table_overview"]

                    metric  value
0                     rows  19037
1                  columns     32
2            unique_pdb_id  19037
3    duplicate_pdb_id_rows      0
4     index_parse_failures      0
5  affinity_parse_failures    114
6      missing_complex_dir      0

## All Columns and Missing Values

In [5]:
report["column_overview"]

                column    dtype  missing  missing_pct  unique
0          line_number    int64        0        0.000   19037
1               pdb_id      str        0        0.000   19037
2           resolution      str        0        0.000     316
3         release_year    int64        0        0.000      35
4         raw_affinity      str        0        0.000    6796
5            reference      str        0        0.000   11413
6          ligand_name      str        0        0.000   12736
7              comment      str        0        0.000   10978
8             raw_line      str        0        0.000   19037
9       index_parse_ok     bool        0        0.000       1
10       affinity_type      str      114        0.599       3
11   affinity_relation      str      114        0.599       3
12      affinity_value  float64      114        0.599    2721
13       affinity_unit      str      114        0.599       5
14      affinity_molar  float64      114        0.599    3836
15           pAffinity  float64      114        0.599    3480
16   affinity_parse_ok     bool        0        0.000       2
17  resolution_numeric  float64      304        1.597     306
18         complex_dir      str        0        0.000   19037
19         year_bucket      str        0        0.000       3
20        protein_path      str        0        0.000   19037
21         has_protein     bool        0        0.000       1
22       protein_bytes    int64        0        0.000   11048
23         pocket_path      str        0        0.000   19037
24          has_pocket     bool        0        0.000       1
25        pocket_bytes    int64        0        0.000    1846
26     ligand_sdf_path      str        0        0.000   19037
27      has_ligand_sdf     bool        0        0.000       1
28    ligand_sdf_bytes    int64        0        0.000    2144
29    ligand_mol2_path      str        0        0.000   19037
30     has_ligand_mol2     bool        0        0.000       1
31   ligand_mol2_bytes    int64        0        0.000    6319

In [6]:
report["column_overview"].sort_values("missing", ascending=False).head(15)

                column    dtype  missing  missing_pct  unique
17  resolution_numeric  float64      304        1.597     306
10       affinity_type      str      114        0.599       3
15           pAffinity  float64      114        0.599    3480
14      affinity_molar  float64      114        0.599    3836
13       affinity_unit      str      114        0.599       5
12      affinity_value  float64      114        0.599    2721
11   affinity_relation      str      114        0.599       3
0          line_number    int64        0        0.000   19037
22       protein_bytes    int64        0        0.000   11048
23         pocket_path      str        0        0.000   19037
20        protein_path      str        0        0.000   19037
24          has_pocket     bool        0        0.000       1
25        pocket_bytes    int64        0        0.000    1846
26     ligand_sdf_path      str        0        0.000   19037
27      has_ligand_sdf     bool        0        0.000       1

## Numeric Features

In [7]:
report["numeric_summary"]

,column,count,mean,std,min,25%,50%,75%,max
0,line_number,19037.0,9525.000000,5495.652873,7.000000e+00,4.766000e+03,9.525000e+03,14284.000000,1.904300e+04
1,release_year,19037.0,2011.642958,5.878284,1.982000e+03,2.008000e+03,2.013000e+03,2016.000000,2.019000e+03
2,affinity_value,18923.0,159.676146,2836.273044,1.700000e-04,9.900000e-01,6.700000e+00,40.145000,2.200000e+05
3,affinity_molar,18923.0,0.000405,0.006676,6.000000e-16,2.000000e-08,3.400000e-07,0.000008,4.000000e-01
4,pAffinity,18923.0,6.401391,1.837780,3.979400e-01,5.096910e+00,6.468521e+00,7.698970,1.522185e+01
5,resolution_numeric,18733.0,2.086523,0.488540,7.500000e-01,1.750000e+00,2.000000e+00,2.400000,4.600000e+00
6,protein_bytes,19037.0,728504.494143,616517.341290,3.547800e+04,3.486240e+05,5.076270e+05,914814.000000,6.984630e+06
7,pocket_bytes,19037.0,106157.629038,26841.216955,1.174500e+04,8.942400e+04,1.048140e+05,122067.000000,2.690010e+05
8,ligand_sdf_bytes,19037.0,4563.601828,3254.490939,4.940000e+02,2.662000e+03,3.675000e+03,5100.000000,2.816500e+04
9,ligand_mol2_bytes,19037.0,6168.829175,4398.008261,7.340000e+02,3.627000e+03,4.973000e+03,6840.000000,3.598300e+04

## Raw Structure File Availability

In [8]:
report["missing_structure_summary"]

     file_type  present  missing  present_pct
0      protein    19037        0        100.0
1       pocket    19037        0        100.0
2   ligand_sdf    19037        0        100.0
3  ligand_mol2    19037        0        100.0

In [9]:
report["missing_examples"]

Empty DataFrame
Columns: [pdb_id, raw_affinity, complex_dir, has_protein, has_pocket, has_ligand_sdf, has_ligand_mol2]
Index: []

## Categorical Feature Counts

In [10]:
for name, table in report["categorical_summaries"].items():
    print(f"\n{name}")
    display(table)

affinity_type

  affinity_type  count
0          IC50   7005
1            Kd   6970
2            Ki   4948
3           NaN    114

affinity_relation

  affinity_relation  count
0                 =  18767
1                 <    149
2               NaN    114
3                <=      7

affinity_unit

  affinity_unit  count
0            uM  10038
1            nM   7809
2            mM    850
3            pM    215
4           NaN    114
5            fM     11

year_bucket

  year_bucket  count
0   2011-2019  12235
1   2001-2010   5691
2   1981-2000   1111

resolution

  resolution  count
0       2.00   1053
1       1.80    855
2       1.90    826
3       2.10    738
4       2.30    710
5       2.20    667
6       2.50    583
7       2.40    579
8       1.70    547
9       1.60    435

## Rows With Unparsed Affinity Labels

These records are useful to inspect before deciding whether to keep inequality/range labels or filter them for a first regression baseline.

In [11]:
raw_df.loc[~raw_df["affinity_parse_ok"].fillna(False), ["pdb_id", "resolution", "release_year", "raw_affinity", "raw_line"]].head(20)

,pdb_id,resolution,release_year,raw_affinity,raw_line
209,1gsf,2.70,1995,IC50~10uM,1gsf 2.70 1995 IC50~10uM // 1gsf.pdf (EAA)
661,1a4m,1.95,1998,Ki~0.1pM,1a4m 1.95 1998 Ki~0.1pM // 1a4m.pdf (PRH)
796,1swp,2.00,1999,Kd~10pM,1swp 2.00 1999 Kd~10pM // 1swp.pdf (BTN)
797,1swk,2.00,1999,Kd~1pM,1swk 2.00 1999 Kd~1pM // 1swk.pdf (BTN)
798,1swn,2.20,1999,Kd~1pM,1swn 2.20 1999 Kd~1pM // 1swn.pdf (BTN)
1468,1kc5,2.50,2002,Kd~0.1uM,1kc5 2.50 2002 Kd~0.1uM // 1kc5.pdf (1...
1689,1n1g,2.50,2003,IC50~5mM,1n1g 2.50 2003 IC50~5mM // 1n1g.pdf (BCP)
1831,1ndj,1.81,2003,Kd~0.69pM,1ndj 1.81 2003 Kd~0.69pM // 1ndj.pdf (BTN)
1832,1n9m,1.60,2003,Kd~11pM,1n9m 1.60 2003 Kd~11pM // 1n9m.pdf (BTN)
1833,1n43,1.89,2003,Kd~28pM,1n43 1.89 2003 Kd~28pM // 1n43.pdf (BTN)
2312,1syo,2.20,2004,Kd~1nM,1syo 2.20 2004 Kd~1nM // 1syo.pdf (M6P)
2313,1sz0,2.10,2004,Kd~1nM,1sz0 2.10 2004 Kd~1nM // 1sz0.pdf (M6P)
3269,2exg,NMR,2006,Kd~50uM,2exg NMR 2006 Kd~50uM // 2exg.pdf (STF)
3849,2ja3,3.05,2007,Kd~100uM,2ja3 3.05 2007 Kd~100uM // 2j9l.pdf (ADP)
3850,2j9l,2.30,2007,Kd~100uM,2j9l 2.30 2007 Kd~100uM // 2j9l.pdf (ATP)
4684,3dba,2.57,2008,Kd~10nM,3dba 2.57 2008 Kd~10nM // 3dba.pdf (35G)
5601,3eor,2.90,2009,Kd~40mM,3eor 2.90 2009 Kd~40mM // 3elc.pdf (C...
6536,3li2,2.20,2010,Kd~1nM,3li2 2.20 2010 Kd~1nM // 3lhs.pdf (S...
6537,3lhs,1.30,2010,Kd~1nM,3lhs 1.30 2010 Kd~1nM // 3lhs.pdf (S...
7235,3ob0,2.85,2011,IC50~1mM,3ob0 2.85 2011 IC50~1mM // 3oay.pdf (2...